# Generated by Django 5.1.2 on 2024-11-10 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('show', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='showorderacceptance',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userorder'),
        ),
        migrations.AddField(
            model_name='showprofile',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.address'),
        ),
        migrations.AddField(
            model_name='showprofile',
            name='camera_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='show.cameraoperator'),
        ),
        migrations.AddField(
            model_name='showprofile',
            name='dancer',
            field=models.ManyToManyField(blank=True, null=True, to='show.dancer'),
        ),
        migrations.AddField(
            model_name='showprofile',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='show.host'),
        ),
        migrations.AddField(
            model_name='showprofile',
            name='photographer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='show.photographer'),
        ),
        migrations.AddField(
            model_name='showprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='showorderacceptance',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.showprofile'),
        ),
        migrations.AddField(
            model_name='showprofile',
            name='singer',
            field=models.ManyToManyField(blank=True, null=True, to='show.singer'),
        ),
    ]
