# Generated by Django 5.1.2 on 2024-11-10 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_initial'),
        ('user', '0002_city_region_remove_address_district_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showprofile',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.address'),
        ),
    ]
