# Generated by Django 5.1.2 on 2024-10-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showprofile',
            name='dancer',
        ),
        migrations.RemoveField(
            model_name='showprofile',
            name='singer',
        ),
        migrations.AddField(
            model_name='showprofile',
            name='dancer',
            field=models.ManyToManyField(blank=True, to='show.dancer'),
        ),
        migrations.AddField(
            model_name='showprofile',
            name='singer',
            field=models.ManyToManyField(blank=True, to='show.singer'),
        ),
    ]
