# Generated by Django 5.1.2 on 2024-10-24 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0003_remove_showprofile_dancer_remove_showprofile_singer_and_more'),
        ('user', '0003_rename_street_address_address_district_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameraoperator',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='show/cameraOperator/profile_images/'),
        ),
        migrations.AddField(
            model_name='cameraoperator',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='show/cameraOperator/videos/'),
        ),
        migrations.AddField(
            model_name='dancer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='show/dancer/profile_images/'),
        ),
        migrations.AddField(
            model_name='dancer',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='show/dancer/videos/'),
        ),
        migrations.AddField(
            model_name='host',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='show/host/profile_images/'),
        ),
        migrations.AddField(
            model_name='host',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='show/host/videos/'),
        ),
        migrations.AddField(
            model_name='photographer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='show/photographer/profile_images/'),
        ),
        migrations.AddField(
            model_name='photographer',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='show/photographer/videos/'),
        ),
        migrations.AddField(
            model_name='showprofile',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.address'),
        ),
        migrations.AddField(
            model_name='singer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='show/singer/profile_images/'),
        ),
        migrations.AddField(
            model_name='singer',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='show/singer/videos/'),
        ),
        migrations.AlterField(
            model_name='showprofile',
            name='dancer',
            field=models.ManyToManyField(blank=True, null=True, to='show.dancer'),
        ),
        migrations.AlterField(
            model_name='showprofile',
            name='singer',
            field=models.ManyToManyField(blank=True, null=True, to='show.singer'),
        ),
    ]
