# Generated by Django 5.1.2 on 2024-10-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_street_address_address_district_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('venue', 'Venue Company'), ('show', 'Show Company')], default='user', max_length=50),
        ),
    ]
