# Generated by Django 5.1.2 on 2024-10-23 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='companyorderacceptance',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userorder'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyorderacceptance',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companyprofile'),
        ),
        migrations.AddField(
            model_name='companycalendar',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companyprofile'),
        ),
    ]
