# Generated by Django 5.1.2 on 2024-10-24 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_companyprofile_user'),
        ('user', '0003_rename_street_address_address_district_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='location',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.address'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='company/profile_images/'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='company/videos/'),
        ),
    ]
